### ISSUE TITLE
TODO: Checkin stuff for RearViewsion project

### ISSUE THREAD

**Issue by truedat101** [IoTone/ShashinGo#3]
Notes from VisionDevCamp

- [ ] Need to track down exactly the version of code used for the ESP32CameraSErver
- [ ] Update license header stuff for this project
- [ ] checkin set up instructions
- [ ] How to build app for VisionPro
- [ ] How to build app for iOS
- [ ] How to build the Arduino app
- [ ] How to discover the wifi for ESP-EYE
- [ ] Is there a way we can advertise a bonjour advertisement to make this something we can find by a link local bonjour name?
- [ ] initial design for 3D printed case .  I couldn't find one to start with, oddly.  I did find the stl files for the device itself.
- [ ] Library code for Swift?
